/**
 * Centralized Turkish UI strings for the Dieter application.
 * All user-facing text lives here for easy future i18n.
 */
export const tr = {
  common: {
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    add: 'Ekle',
    search: 'Ara',
    loading: 'Yükleniyor...',
    error: 'Bir hata oluştu',
    success: 'Başarılı',
    confirm: 'Onayla',
    close: 'Kapat',
    back: 'Geri',
    next: 'İleri',
    yes: 'Evet',
    no: 'Hayır',
    required: 'Zorunlu alan',
    optional: 'İsteğe bağlı',
    noResults: 'Sonuç bulunamadı',
    actions: 'İşlemler',
    details: 'Detaylar',
    copy: 'Kopyala',
    duplicate: 'Çoğalt',
    total: 'Toplam',
    average: 'Ortalama',
    perDay: 'Günlük',
    logout: 'Çıkış Yap',
    settings: 'Ayarlar',
    appName: 'Dieter',
    appDescription: 'Diyetisyenler için diyet planı yönetim aracı',
  },

  auth: {
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    confirmPassword: 'Şifre Tekrar',
    displayName: 'Ad Soyad',
    clinicName: 'Klinik Adı',
    clinicNameHint: 'İsteğe bağlı — PDF çıktılarında görünür',
    forgotPassword: 'Şifremi Unuttum',
    noAccount: 'Hesabın yok mu?',
    hasAccount: 'Zaten hesabın var mı?',
    registerNow: 'Şimdi kayıt ol',
    loginNow: 'Giriş yap',
    loginError: 'E-posta veya şifre hatalı',
    registerError: 'Kayıt sırasında bir hata oluştu',
    registerSuccess: 'Kayıt başarılı! Giriş yapabilirsiniz.',
    passwordMismatch: 'Şifreler eşleşmiyor',
    passwordTooShort: 'Şifre en az 8 karakter olmalı',
    invalidEmail: 'Geçerli bir e-posta adresi girin',
  },

  nav: {
    dashboard: 'Ana Sayfa',
    clients: 'Danışanlar',
    foods: 'Yiyecekler',
    plans: 'Diyet Planları',
    templates: 'Şablonlar',
    settings: 'Ayarlar',
  },

  clients: {
    title: 'Danışanlar',
    addClient: 'Danışan Ekle',
    editClient: 'Danışanı Düzenle',
    deleteClient: 'Danışanı Sil',
    deleteConfirm: 'Bu danışanı silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
    name: 'Ad Soyad',
    birthdate: 'Doğum Tarihi',
    age: 'Yaş',
    height: 'Boy (cm)',
    weight: 'Kilo (kg)',
    goal: 'Hedef',
    notes: 'Notlar',
    noPlan: 'Henüz diyet planı yok',
    clientCount: 'danışan',
    lastPlan: 'Son plan',
    searchPlaceholder: 'Danışan ara...',
    goalPlaceholder: 'Örn: 5 kg vermek, kas kütlesi artırmak',
    notesPlaceholder: 'Serbest notlar...',
  },

  foods: {
    title: 'Yiyecekler',
    search: 'Yiyecek Ara',
    searchPlaceholder: 'Yiyecek adı yazın...',
    name: 'Yiyecek İsmi',
    addManual: 'Manuel Ekle',
    addDish: 'Tarif / Yemek Ekle',
    editFood: 'Yiyeceği Düzenle',
    deleteFood: 'Yiyeceği Sil',
    deleteConfirm: 'Bu yiyeceği silmek istediğinize emin misiniz?',
    notFound: 'Bulamadın mı?',
    notFoundCta: 'Buradan ekle →',
    category: 'Kategori',
    servingSize: 'Porsiyon',
    servingUnit: 'Birim',
    calories: 'Kalori',
    caloriesShort: 'kcal',
    protein: 'Protein',
    proteinShort: 'P',
    carbohydrate: 'Karbonhidrat',
    carbsShort: 'K',
    fat: 'Yağ',
    fatShort: 'Y',
    fiber: 'Lif',
    sugar: 'Şeker',
    saturatedFat: 'Doymuş Yağ',
    sodium: 'Sodyum',
    cholesterol: 'Kolesterol',
    glycemicIndex: 'Glisemik İndeks',
    allergens: 'Alerjenler',
    detailedInfo: 'Detaylı Bilgi',
    vitamins: 'Vitaminler',
    minerals: 'Mineraller',
    ingredients: 'Malzemeler',
    addIngredient: 'Malzeme Ekle',
    totalNutrients: 'Toplam Besin Değeri',
    perServing: 'Porsiyon Başına',
    dishServingHint: '1 porsiyon = kaç gram?',
    conversionFactor: 'Gram Karşılığı',
    conversionHint: 'Bu birimde 1 adet kaç gram?',
    source: 'Kaynak',
    sourceManual: 'Manuel giriş',
    sourceFatsecret: 'FatSecret',
    sourceUsda: 'USDA',
    sourceDish: 'Tarif',
    myFoods: 'Yiyeceklerim',
    globalFoods: 'Genel Yiyecekler',
    externalResults: 'Dış Kaynak Sonuçları',
    importFood: 'Ekle',
    nameRequired: 'Yiyecek adı zorunlu',
    caloriesRequired: 'Kalori değeri zorunlu',
  },

  plans: {
    title: 'Diyet Planları',
    newPlan: 'Yeni Plan',
    newPlanForClient: 'Yeni Plan Oluştur',
    fromTemplate: 'Şablondan Başla',
    editPlan: 'Planı Düzenle',
    deletePlan: 'Planı Sil',
    deleteConfirm: 'Bu planı silmek istediğinize emin misiniz?',
    planTitle: 'Plan Başlığı',
    planTitlePlaceholder: 'Örn: Haziran Ayı Beslenme Planı',
    planNotes: 'Plan Notları',
    day: 'Gün',
    addDay: 'Gün Ekle',
    removeDay: 'Günü Sil',
    duplicateDay: 'Günü Kopyala',
    dayLabel: 'Gün Etiketi',
    dayNotes: 'Gün Notları',
    meal: 'Öğün',
    mainMeal: 'Ana Öğün',
    snack: 'Ara Öğün',
    addMeal: 'Öğün Ekle',
    removeMeal: 'Öğünü Sil',
    duplicateMeal: 'Öğünü Kopyala',
    mealLabel: 'Öğün Adı',
    mealLabelPlaceholder: 'Örn: Kahvaltı, Öğle Yemeği',
    mealTime: 'Saat',
    addFood: 'Yiyecek Ekle',
    quantity: 'Miktar',
    unit: 'Birim',
    removeItem: 'Kaldır',
    saveAsTemplate: 'Şablon Olarak Kaydet',
    exportPdf: 'PDF Oluştur',
    nutritionSummary: 'Besin Özeti',
    dayTotal: 'Gün Toplamı',
    planTotal: 'Plan Toplamı',
    planAverage: 'Günlük Ortalama',
    selectClient: 'Danışan Seç',
    noClient: 'Danışan yok (Şablon)',
    templateSaved: 'Şablon olarak kaydedildi',
    pdfGenerated: 'PDF oluşturuldu',
    allPlans: 'Tüm Planlar',
    clientPlans: 'Danışan Planları',
  },

  templates: {
    title: 'Şablonlar',
    useTemplate: 'Şablonu Kullan',
    editTemplate: 'Şablonu Düzenle',
    deleteTemplate: 'Şablonu Sil',
    deleteConfirm: 'Bu şablonu silmek istediğinize emin misiniz?',
    starterTemplates: 'Başlangıç Şablonları',
    myTemplates: 'Şablonlarım',
  },

  settings: {
    title: 'Ayarlar',
    profile: 'Profil',
    displayName: 'Görünen Ad',
    clinicName: 'Klinik Adı',
    logo: 'Logo',
    uploadLogo: 'Logo Yükle',
    saved: 'Ayarlar kaydedildi',
  },

  pdf: {
    title: 'Diyet Planı',
    preparedBy: 'Hazırlayan',
    preparedFor: 'Danışan',
    date: 'Tarih',
    notes: 'Notlar',
    page: 'Sayfa',
    createdWith: 'Dieter ile oluşturuldu',
  },

  nutrients: {
    calories: 'Kalori (kcal)',
    protein: 'Protein (g)',
    carbohydrate: 'Karbonhidrat (g)',
    fat: 'Yağ (g)',
    fiber: 'Lif (g)',
    sugar: 'Şeker (g)',
    saturatedFat: 'Doymuş Yağ (g)',
    sodium: 'Sodyum (mg)',
    cholesterol: 'Kolesterol (mg)',
    vitaminA: 'A Vitamini (mcg)',
    vitaminC: 'C Vitamini (mg)',
    vitaminD: 'D Vitamini (mcg)',
    vitaminE: 'E Vitamini (mg)',
    vitaminK: 'K Vitamini (mcg)',
    vitaminB1: 'B1 Vitamini (mg)',
    vitaminB2: 'B2 Vitamini (mg)',
    vitaminB3: 'B3 Vitamini (mg)',
    vitaminB6: 'B6 Vitamini (mg)',
    vitaminB12: 'B12 Vitamini (mcg)',
    folate: 'Folat (mcg)',
    calcium: 'Kalsiyum (mg)',
    iron: 'Demir (mg)',
    potassium: 'Potasyum (mg)',
    magnesium: 'Magnezyum (mg)',
    zinc: 'Çinko (mg)',
  },

  days: {
    monday: 'Pazartesi',
    tuesday: 'Salı',
    wednesday: 'Çarşamba',
    thursday: 'Perşembe',
    friday: 'Cuma',
    saturday: 'Cumartesi',
    sunday: 'Pazar',
  },

  defaultMealLabels: {
    breakfast: 'Kahvaltı',
    morningSnack: 'Kuşluk',
    lunch: 'Öğle Yemeği',
    afternoonSnack: 'İkindi',
    dinner: 'Akşam Yemeği',
    eveningSnack: 'Gece Atıştırması',
  },
} as const;
